version: '3'

services:

  api:
    build: .
    image: vanister/contacts_api
    depends_on:
      - localstack
    ports:
      - '3000:3000'
    container_name: contacts_api

    # these are the environment variables that are used in the api
    environment:
      AWS_ENDPOINT: 'http://dynamodb_localstack:8000' # localstack container host for dynamodb
      AWS_REGION: 'us-west-1'
      AWS_ACCESS_KEY_ID: 'componse-fake-access-key'
      AWS_SECRET_ACCESS_KEY: 'compose-fake-secret-key'

  localstack:
    image: localstack/localstack:latest
    ports:
      - '8000:8000' # using port 8000 to be consistent with dynamodb local jar
      - '8080:8080' # the localstack admin portal
    container_name: dynamodb_localstack
    environment:
      SERVICES: dynamodb:8000
      DATA_DIR: '/tmp/localstack/data'
